---
- name: config nginx + custom image
  hosts: server
  become: yes

  vars:
    web_root: /var/www/html
    page_url: "https://www.sheldonbrown.com/org/web_sample1.html"
    page_file: web_sample1.html
    img_dir: images
    custom_img: custom.jpg
    listen_port: "{{ lookup('ansible.builtin.env','PORT',default='80') }}"
    heading: "Welcome to My Site"

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes

    - name: Update nginx listen port
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen\s*\d+'
        line:     listen {{ listen_port }};
        backrefs: yes

    - name: Render index.html from template
      template:
        src: index.html.j2
        dest: "{{ web_root }}/index.html"

    - name: Download original page
      get_url:
        url: "{{ page_url }}"
        dest: "{{ web_root }}/{{ page_file }}"
        mode: '0644'

    - name: Ensure images directory exists
      file:
        path: "{{ web_root }}/{{ img_dir }}"
        state: directory
        mode: '0755'

    - name: Upload custom image from controller
      copy:
        src: "{{ playbook_dir }}/{{ custom_img }}"
        dest: "{{ web_root }}/{{ img_dir }}/{{ custom_img }}"
        mode: '0644'

    - name: Replace <img> src in downloaded HTML
      replace:
        path: "{{ web_root }}/{{ page_file }}"
        regexp: '(<img\s+[^>]*src=")[^"]*(")'
        replace: '\1/{{ img_dir }}/{{ custom_img }}\2'

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

