---
- name: config nginx + external image
  hosts: server
  become: yes

  vars:
    web_root: /var/www/html
    page_url: "https://www.sheldonbrown.com/org/web_sample1.html"
    page_file: web_sample1.html
    image_src_url: "https://ibb.co/h1MhgjgW"
    listen_port: "{{ lookup('ansible.builtin.env','PORT',default='80') }}"
    heading: "Welcome to My Site"

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes

    - name: Update nginx listen port
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen\s*\d+'
        line:     listen {{ listen_port }};
        backrefs: yes

    - name: Render index.html from template
      template:
        src: index.html.j2
        dest: "{{ web_root }}/index.html"

    - name: Download original page
      get_url:
        url: "{{ page_url }}"
        dest: "{{ web_root }}/{{ page_file }}"
        mode: '0644'

    - name: Replace <img> src in downloaded HTML with external link
      replace:
        path: "{{ web_root }}/{{ page_file }}"
        regexp: '(<img\s+[^>]*src=")[^"]*(")'
        replace: '\1{{ image_src_url }}\2'

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

