#cloud-config
package_update: true
packages:
  - curl
runcmd:
  - |
    TOKEN=$(curl -sX PUT "http://169.254.169.254/latest/api/token" \
      -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
    IPV4=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 \
      -H "X-aws-ec2-metadata-token: $TOKEN")
    curl -X POST \
      --user shapi:11172ce7b693cd4138caf86996fc1b79e3 \
      "http://vpn.aws.cts.care:8080/job/dor-test/buildWithParameters?PORT=6789&HOST=${IPV4}"

